#ifndef LV_CONF_H
#define LV_CONF_H

#ifndef UI_COLOR_256
#define UI_COLOR_256 1
#endif

#ifndef UI_COLOR_565
#define UI_COLOR_565 0
#endif

#if UI_COLOR_256 && UI_COLOR_565
#warning "UI_COLOR_565 overrides UI_COLOR_256"
#endif

#ifndef UI_LV_MEM_SIZE_KB
#define UI_LV_MEM_SIZE_KB 160
#endif

#ifndef UI_ENABLE_MEM_MONITOR
#define UI_ENABLE_MEM_MONITOR 1
#endif

#ifndef UI_ENABLE_PERF_MONITOR
#define UI_ENABLE_PERF_MONITOR 0
#endif

#if UI_COLOR_565
#define LV_COLOR_DEPTH 16
#elif UI_COLOR_256
#define LV_COLOR_DEPTH 8
#else
#define LV_COLOR_DEPTH 16
#endif

#define LV_COLOR_16_SWAP 0

#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (UI_LV_MEM_SIZE_KB * 1024U)

#define LV_USE_LOG 0
#define LV_USE_ASSERT_NULL 0
#define LV_USE_ASSERT_MALLOC 0
#define LV_USE_ASSERT_STYLE 0
#define LV_USE_ASSERT_MEM_INTEGRITY 0
#define LV_USE_ASSERT_OBJ 0

#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_18 0
#define LV_FONT_MONTSERRAT_24 0
#define LV_FONT_MONTSERRAT_28 0
#define LV_FONT_MONTSERRAT_32 0
#define LV_FONT_MONTSERRAT_40 0

#define LV_USE_ARC 0
#define LV_USE_BAR 0
#define LV_USE_BTN 1
#define LV_USE_BTNMATRIX 0
#define LV_USE_CANVAS 0
#define LV_USE_CHECKBOX 0
#define LV_USE_DROPDOWN 0
#define LV_USE_IMG 1
#define LV_USE_LABEL 1
#define LV_LABEL_TEXT_SELECTION 0
#define LV_LABEL_LONG_TXT_HINT 1
#define LV_USE_LINE 1
#define LV_USE_ROLLER 0
#define LV_USE_SLIDER 0
#define LV_USE_SWITCH 0
#define LV_USE_TEXTAREA 0
#define LV_USE_TABLE 0
#define LV_USE_ANIMIMG 0
#define LV_USE_CALENDAR 0
#define LV_USE_CHART 0
#define LV_USE_COLORWHEEL 0
#define LV_USE_IMGBTN 0
#define LV_USE_KEYBOARD 0
#define LV_USE_LED 0
#define LV_USE_LIST 1
#define LV_USE_MENU 0
#define LV_USE_METER 0
#define LV_USE_MSGBOX 0
#define LV_USE_SPAN 0
#define LV_USE_SPINBOX 0
#define LV_USE_SPINNER 0
#define LV_USE_TABVIEW 0
#define LV_USE_TILEVIEW 0
#define LV_USE_WIN 0
#define LV_USE_THEME_DEFAULT 0

#define LV_USE_PERF_MONITOR UI_ENABLE_PERF_MONITOR
#define LV_USE_MEM_MONITOR UI_ENABLE_MEM_MONITOR

#endif  // LV_CONF_H
